services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
