name: Smoothstart CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Create .env file
      run: |
        echo POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_HOST=${{ vars.POSTGRES_HOST }} >> .env
        echo POSTGRES_DB=${{ vars.POSTGRES_DB }} >> .env
        echo POSTGRES_USER=${{ vars.POSTGRES_USER }} >> .env
        echo REDIS_HOST=${{ vars.REDIS_HOST }} >> .env
        echo REDIS_PORT=${{ vars.REDIS_PORT }} >> .env
        echo SECRET_KEY=${{ vars.SECRET_KEY }} >> .env

    - name: Build
      run: make build

    - name: Run
      run: make run
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          username: ${{ secret.SSH_USER }}
          key: ${{ secret.SSH_PRIVATE_KEY }}
          port: ${{ secret.SSH_PORT }}
          source: "."
          target: "/home/admin/domains/smoothstart.proxilius.eu/public_html" 

      - name: Upload .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          username: ${{ secret.SSH_USER }}
          key: ${{ secret.SSH_PRIVATE_KEY }}
          port: ${{ secret.SSH_PORT }}
          source: ".env"
          target: "/home/admin/domains/smoothstart.proxilius.eu/public_html/.env"

      - name: Start application on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          username: ${{ secret.SSH_USER }}
          key: ${{ secret.SSH_PRIVATE_KEY }}
          port: ${{ secret.SSH_PORT }}
          script: |
            cd /home/admin/domains/smoothstart.proxilius.eu/public_html          
            make build
            make run


